# Generated by Django 4.2.30 on 2026-09-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='coffee', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CoffeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('origin', models.CharField(blank=True, default='Single Estate', max_length=150)),
                ('altitude', models.CharField(blank=True, default='1,800 MASL', max_length=50)),
                ('process_method', models.CharField(blank=True, default='Washed', max_length=100)),
                ('roast_level', models.CharField(default='Medium Roast', max_length=50)),
                ('tasting_notes', models.CharField(blank=True, help_text='Comma separated, e.g. Jasmine, Peach, Citrus', max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('review_count', models.IntegerField(default=120)),
                ('image_url', models.URLField(max_length=500)),
                ('is_signature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffees', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Tasting Notes', max_length=100)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Guest Coffee Enthusiast', max_length=100)),
                ('customer_email', models.EmailField(blank=True, default='guest@artisanalcoffee.com', max_length=254)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BREWING', 'Brewing in Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BREWING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temperature', models.CharField(default='Hot', max_length=20)),
                ('milk_choice', models.CharField(default='Oat Silk (Barista)', max_length=50)),
                ('coffee_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coffeeitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
        ),
    ]
