# Generated by Django 4.2.30 on 2026-10-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeeitem',
            options={'ordering': ['id']},
        ),
    ]
