# Generated by Django 4.2.30 on 2026-10-03 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_coffeeitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
