/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#2c1600", 
        "inverse-primary": "#835058", 
        "on-primary-fixed-variant": "#683941", 
        "tertiary-container": "#2f1d00", 
        "on-surface": "#e5e2e1", 
        "on-primary": "#4e232b", 
        "on-background": "#e5e2e1", 
        "surface": "#131313", 
        "surface-container-low": "#1c1b1b", 
        "error-container": "#93000a", 
        "inverse-surface": "#e5e2e1", 
        "surface-container-high": "#2a2a2a", 
        "surface-container-lowest": "#0e0e0e", 
        "on-tertiary": "#442c00", 
        "outline-variant": "#514345", 
        "surface-container-highest": "#353535", 
        "tertiary": "#fbbb50", 
        "primary-fixed-dim": "#f7b5be", 
        "background": "#131313", 
        "surface-tint": "#f7b5be", 
        "on-error": "#690005", 
        "on-primary-container": "#b37981", 
        "on-surface-variant": "#d5c2c3", 
        "secondary-container": "#df8600", 
        "on-secondary-container": "#4d2b00", 
        "inverse-on-surface": "#313030", 
        "outline": "#9e8d8e", 
        "primary": "#f7b5be", 
        "on-tertiary-fixed-variant": "#614000", 
        "primary-container": "#3b141c", 
        "surface-dim": "#131313", 
        "surface-container": "#20201f", 
        "tertiary-fixed": "#ffddaf", 
        "on-secondary-fixed-variant": "#693c00", 
        "on-tertiary-fixed": "#281800", 
        "tertiary-fixed-dim": "#fbbb50", 
        "surface-bright": "#393939", 
        "secondary-fixed": "#ffdcbd", 
        "on-secondary": "#492900", 
        "on-primary-fixed": "#340f17", 
        "on-error-container": "#ffdad6", 
        "primary-fixed": "#ffd9dd", 
        "error": "#ffb4ab", 
        "surface-variant": "#353535", 
        "secondary-fixed-dim": "#ffb86e", 
        "secondary": "#ffb86e", 
        "on-tertiary-container": "#b57d12"
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        display: ['Playfair Display', 'serif'],
        headline: ['Playfair Display', 'serif'],
        "label-lg": ["Manrope"],
        "headline-sm": ["Playfair Display"],
        "body-lg": ["Manrope"],
        "label-md": ["Manrope"],
        "body-md": ["Manrope"],
        "display-lg-mobile": ["Playfair Display"],
        "body-sm": ["Manrope"],
        "title-lg": ["Manrope"],
        "display-lg": ["Playfair Display"],
        "label-sm": ["Manrope"],
        "title-md": ["Manrope"],
        "headline-md": ["Playfair Display"],
        "headline-lg": ["Playfair Display"]
      },
      fontSize: {
        "label-lg": ["14px", {"lineHeight": "18px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-sm": ["18px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "26px", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "22px", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-sm": ["12px", {"lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "title-lg": ["18px", {"lineHeight": "26px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "display-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["10px", {"lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "700"}],
        "title-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-md": ["22px", {"lineHeight": "30px", "letterSpacing": "0em", "fontWeight": "600"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};
