# Generated by Django 4.2.30 on 2026-09-30 13:37

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Bole, Kazanchis, Kirkos, Old Airport', max_length=100)),
                ('delivery_fee_etb', models.DecimalField(decimal_places=2, help_text='Delivery fee in ETB', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Store Pickup'), ('DINE_IN', 'Dine-In (Table Service)')], default='DELIVERY', max_length=20)),
                ('table_number', models.CharField(blank=True, help_text='For Dine-In orders', max_length=20)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=20, validators=[apps.accounts.models.validate_ethiopian_phone])),
                ('delivery_address', models.TextField(blank=True, help_text='Snapshot of full address at time of order')),
                ('subtotal_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee_etb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PLACED', 'Placed (Paid)'), ('ACCEPTED', 'Accepted by Kitchen'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup / Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled by Customer'), ('REJECTED', 'Rejected by Manager')], db_index=True, default='PENDING_PAYMENT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('estimated_prep_minutes', models.PositiveIntegerField(default=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliveryzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('variant_name', models.CharField(blank=True, max_length=100)),
                ('unit_price_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature', models.CharField(default='Hot', max_length=20)),
                ('milk_choice', models.CharField(default='Oat Silk (Barista)', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, help_text='Master toggle to accept new orders')),
                ('opening_hours', models.CharField(default='Mon - Sun: 7:00 AM - 10:00 PM', max_length=200)),
                ('default_prep_minutes', models.PositiveIntegerField(default=20)),
                ('contact_phone', models.CharField(default='+251911234567', max_length=20, validators=[apps.accounts.models.validate_ethiopian_phone])),
                ('contact_email', models.EmailField(default='hello@artisanalcoffee.com', max_length=254)),
                ('address', models.CharField(default='Bole Medhanialem, Addis Ababa, Ethiopia', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PLACED', 'Placed (Paid)'), ('ACCEPTED', 'Accepted by Kitchen'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup / Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled by Customer'), ('REJECTED', 'Rejected by Manager')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_name', models.CharField(max_length=100)),
                ('price_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='orders.orderitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
    ]
