# Generated by Django 4.2.30 on 2026-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='milk_choice',
            field=models.CharField(blank=True, default='Oat Silk (Barista)', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='temperature',
            field=models.CharField(blank=True, default='Hot', max_length=20),
        ),
    ]
