# Generated by Django 4.2.30 on 2026-10-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_milk_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_prep_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Filled from RestaurantSettings.default_prep_minutes when the order is placed'),
        ),
    ]
