# Generated by Django 4.2.30 on 2026-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='Addis Ababa', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='subcity_or_zone',
            field=models.CharField(blank=True, help_text='e.g., Bole, Kirkos, Kazanchis', max_length=100),
        ),
    ]
