# Generated by Django 4.2.30 on 2026-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_city_alter_address_subcity_or_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Frontend URL to navigate to when the notification is clicked', max_length=500),
        ),
    ]
