# Generated by Django 4.2.30 on 2026-09-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_ref', models.CharField(db_index=True, max_length=100, unique=True)),
                ('chapa_reference', models.CharField(blank=True, max_length=100)),
                ('amount_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('ABANDONED', 'Payment Abandoned')], default='PENDING', max_length=20)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('raw_response', models.TextField(blank=True, help_text='JSON response dump from Chapa API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
