# Generated by Django 4.2.30 on 2026-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('telebirr', 'Telebirr'), ('cbebirr', 'CBE Birr'), ('mpesa', 'M-Pesa'), ('awashbirr', 'Awash Birr'), ('ebirr', 'E-Birr'), ('card', 'Credit / Debit Card'), ('cash', 'Cash on Delivery')], default='telebirr', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for mobile payment', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('ABANDONED', 'Payment Abandoned / Cancelled')], default='PENDING', max_length=20),
        ),
    ]
